### ISSUE TITLE
Exception when trying to send file to archive

### ISSUE THREAD

**Issue by boxerab** [gunterze/dcm4chee-arc#2]
I get the following exception when trying to send a study to the archive:

Failed to create file:: java.lang.IllegalStateException: 
Illegal character in opaque part at index 7: file:C:\src\dcm4chee\jboss-as-7.1.1.Final\standalone\data
at org.dcm4chee.archive.entity.FileSystem.getDirectory(FileSystem.java:159) 

I am on windows. It looks like java doesn't like the back slash.

Thanks.

**Comment by boxerab** [comment]
I traced this back to the file system uri in the database: Table filesystem, Column fs_uri.

This value should be in the following format for windows:

 file:///C:/src/dcm4chee/jdboss-as-7.1.1.Final/standalone/data

Changing this value results in successful send.

**Comment by gunterze** [comment]
The problem is caused by the value

```
dcmInitFileSystemURI: file:${jboss.server.data.dir}
```

in the sample configuration DCM4CHEE-ARC/ldap/sample-config.ldif, which does not specify a valid URI on Windows.

For a similar reason, processing of HL7 v2.x ADT messages, and attribute coercions will not work on Windows.
To fix it, replace

```
file:${jboss.server.data.dir}
```

by the URI of your JBoss 7 data directory, e.g.:

```
file:/C:/jboss-as-7.1.1.Final/standalone/data
```

and

```
file:${jboss.server.config.dir}
```

by the URI of your JBoss 7 configuration directory, e.g.:

```
file:/C:/jboss-as-7.1.1.Final/standalone/configuration
```

before importing the sample configuration into LDAP.

Corresponding dcm4chee-arc JIRA issue: [ARCH-6](http://www.dcm4che.org/jira/browse/ARCH-6)

**Comment by gunterze** [comment]
Solved with JIRA issue: [ARCH-7](http://www.dcm4che.org/jira/browse/ARCH-7)
